### ISSUE TITLE
Installation instructions are incomplete

### ISSUE THREAD

**Issue by thetuxinator** [alexgit2k/trac-gitlab-service-hook#1]
Hi,

The installation instructions are incomplete, no word on pip install or easy_install and there is no setup.py

Would be perfect if that can be provided

kind regards

Mike

**Comment by alexgit2k** [comment]
You only need to copy gitlabservicehook.py into the project's plugins dir as written in the [README.md](/alexgit2k/trac-gitlab-service-hook/blob/master/README.md)

Feel free to add additional setup-methods.
